/**
 * Created by 陈伟达 on 2017/8/24.
 */

export const MAIN_PAGE_CHATTER_TEXTCHANGE = 'MAIN_PAGE_CHATTER_TEXTCHANGE';

export const PROFILE_PAGE_ZIP_TEXTCHANGE = 'PROFILE_PAGE_ZIP_TEXTCHANGE';
export const PROFILE_PAGE_PRESS_STATE_CHANGE = 'PROFILE_PAGE_PRESS_STATE_CHANGE';
export const PROFILE_PAGE_CHECK_STATE_CHANGE = 'PROFILE_PAGE_CHECK_STATE_CHANGE';
export const FETCH_PROFILE_DATA_REQUEST = 'FETCH_PROFILE_DATA_REQUEST';
export const FETCH_PROFILE_DATA_SUCCESS = 'FETCH_PROFILE_DATA_SUCCESS';
export const FETCH_PROFILE_DATA_FAILURE = 'FETCH_PROFILE_DATA_FAILURE';

export const CLICK_TAB = 'CLICK_TAB';

export const FETCH_MESSAGE_LIST_REQUEST = 'FETCH_MESSAGE_LIST_REQUEST';
export const FETCH_MESSAGE_LIST_SUCCESS = 'FETCH_MESSAGE_LIST_SUCCESS';
export const FETCH_MESSAGE_LIST_FAILURE = 'FETCH_MESSAGE_LIST_FAILURE';
export const LOAD_MORE_MESSAGE_LIST_REQUEST = 'LOAD_MORE_MESSAGE_LIST_REQUEST';
export const LOAD_MORE_MESSAGE_LIST_SUCCESS = 'LOAD_MORE_MESSAGE_LIST_SUCCESS';
export const LOAD_MORE_MESSAGE_LIST_FAILURE = 'LOAD_MORE_MESSAGE_LIST_FAILURE';
